version: '3'

services:
  dev:
    container_name: pdf_print_example
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - .:/app
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
